#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new App\Command\MergeCommand());
$application->add(new App\Command\RemoveDuplicatePointsCommand());
$application->add(new App\Command\SplitCommand());
$application->add(new App\Command\StatCommand());

$application->run();
